### ISSUE TITLE
Add Interactivity to form fields via react state

### ISSUE THREAD

**Issue by clarkenciel** [proud-dogs/rollercoaster#1]
Why:
Users need to be able to enter data into the fields of a LoanEntry.

Acceptance:
- Users can enter data into the fields of a LoanEntry
- Data does not get mixed up among entries

**Comment by fakemonster** [comment]
Resolved via [b9ce75](https://github.com/proud-dogs/rollercoaster/commit/b9ce759418a094755c3d738d8d04b634280324a5)
