### ISSUE TITLE
write calculateRepaymentPeriod

### ISSUE THREAD

**Issue by clarkenciel** [proud-dogs/rollercoaster#13]
calculateRepaymentPeriod(loan, monthlyPayment) -> Number

**Comment by fakemonster** [comment]
new data structures mean this function can now just be:
calculateRepaymentPeriod(loan) -> Number

Also research indicates that the most appropriate phrase for this is "term", or "repayment term", so let's go with repaymentTerm as our variable

**Comment by fakemonster** [comment]
this actually already existed, now `calculateRepaymentTerm` as of #22
