### ISSUE TITLE
Add interactivity to calculate button via react state

### ISSUE THREAD

**Issue by clarkenciel** [proud-dogs/rollercoaster#4]
Why:
Users need to be able to calculate a "finished paying" date according to the loan information provided.

Criteria:
A date is displayed to the user when they click "Calculate Loans"
The date is an accurate prediction of when the loan will be paid off given monthly payments, interest rate and current loan amount.

**Comment by fakemonster** [comment]
Handled via [e7f6c2](https://github.com/proud-dogs/rollercoaster/commit/8c8d93a190c119d44e082a424a45da0a6335258a)
